# Generated by Django 3.1.4 on 2021-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
